apiVersion: v1
kind: Secret

metadata:
  name: account-secret

type: Opaque

# --- Cấu hình cũ (dùng base64) ---
# data:
#   DB_USERNAME: cm9vdA==
#   DB_PASSWORD: cm9vdA==

# --- Cấu hình mới (dùng stringData, dễ đọc và sửa) ---
stringData:
  DB_USERNAME: root
  DB_PASSWORD: root
